"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
/* Copyright 2021 i2c Inc. All rights reserved. */
var index_1 = require("../../base/src/index");
var styles = index_1.css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    :host {\n        position: fixed;\n        left: 0;\n        top: 0;\n        display: flex;\n        align-items: center;\n        justify-content: center;\n        box-sizing: border-box;\n        width: 100vw;\n        height: 100vh;\n        height: -webkit-fill-available;\n        height: fill-available;\n        visibility: hidden;\n        pointer-events: none;\n        z-index: 2;\n        transition: visibility 0ms linear var(--cm-global-animation-duration-100, .13s)\n    }\n\n    :host([open]) {\n        visibility: visible\n    }\n\n    @media only screen and (max-device-height: 350px), only screen and (max-device-width: 400px) {\n        :host([responsive]) {\n            width: 100%;\n            height: 100%;\n            max-width: 100%;\n            max-height: 100%;\n            border-radius: 0;\n            margin-top: 0\n        }\n    }\n"], ["\n    :host {\n        position: fixed;\n        left: 0;\n        top: 0;\n        display: flex;\n        align-items: center;\n        justify-content: center;\n        box-sizing: border-box;\n        width: 100vw;\n        height: 100vh;\n        height: -webkit-fill-available;\n        height: fill-available;\n        visibility: hidden;\n        pointer-events: none;\n        z-index: 2;\n        transition: visibility 0ms linear var(--cm-global-animation-duration-100, .13s)\n    }\n\n    :host([open]) {\n        visibility: visible\n    }\n\n    @media only screen and (max-device-height: 350px), only screen and (max-device-width: 400px) {\n        :host([responsive]) {\n            width: 100%;\n            height: 100%;\n            max-width: 100%;\n            max-height: 100%;\n            border-radius: 0;\n            margin-top: 0\n        }\n    }\n"])));
exports["default"] = styles;
var templateObject_1;
